### PR TITLE
Modernisation & Uniform Initialisation Syntax 

### PR DESCRIPTION
**Pull request by lunik1**
A bit more tidying up, and switching to use C++11 features. Includes switch to C++11 uniform initialisation syntax.

### CODE REVIEW

**Comment by davidcarbonis** [comment]
Updates to the BTagCallibration code is probably not worth the effort updating as it is centrally provided by CMSSW and is liable to future updates (the current incarnation is current the latest stable version with a new one expected before TOP2016).

Only other remark is a preference to continue using the root implementation for the random gaussian smearing as the time seed used ensures that there is a greater degree of "randomness" than std::random_device{} which will on certain platforms (Windows) spit out a non non-deterministic sequence ... and I am more familiar with the ROOT classes (and are easier to follow for the less expert user).

**Comment by lunik1** [comment]
Nice catch on std::random_device! Reverted.

I didn't realise the BTagCalibration code was from CMSSW, reverted back to the version currently on master.

**Comment by davidcarbonis** [comment]
Cheers! Only query:
- is the log file necessary?

**Comment by lunik1** [comment]
Hmm not quite sure what happened to that commit, fixed now!

**Comment by lunik1** [comment]
Ta! Maybe I'll do some real work now 😛

**Comment by davidcarbonis** [comment]
Now I'll need to understand what's broken the plots ... Don't worry, I'll own up if it was me :P

**Pull request merged**
